'use strict';
const $=s=>document.querySelector(s),storageKey='cube-studio-v1';
let state={schema:'cube-studio',version:1,name:'My cube setup',width:30,height:30,depth:30,back:true,cubes:[]},past=[],future=[],selected=null,mode='add';
const multiSelection=new Set();
const appearance=()=>({material:$('#material').value,color:$('#color').value});
function preset(shape){return (shape==='single'?[[0,0,0]]:shape==='tower'?[[0,0,0],[0,1,0],[0,2,0]]:shape==='steps'?[[0,0,0],[1,0,0],[2,0,0],[0,1,0],[1,1,0],[0,2,0]]:[[0,0,0],[1,0,0],[0,1,0],[1,1,0]]).map(([x,y,z])=>({x,y,z,...appearance()}));}
state.cubes=preset('grid');
try{const saved=localStorage.getItem(storageKey);if(saved)state=CubeModel.migrate(JSON.parse(saved));}catch(e){$('#status').textContent='Saved design could not be restored; starting a new layout.';}
state=CubeModel.migrate(state);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e8e9e2');
const camera=new THREE.PerspectiveCamera(38,1,.1,10000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$('#viewer').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight('#ffffff','#8d9983',2.5));const light=new THREE.DirectionalLight('#ffffff',2);light.position.set(100,250,180);scene.add(light);
const tableGroup=new THREE.Group();scene.add(tableGroup);
const root=new THREE.Group(),hits=new THREE.Group(),slots=new THREE.Group();scene.add(root,hits,slots);
const grid=new THREE.GridHelper(1400,40,'#bdc8b7','#d3dacb');grid.position.y=-.5;scene.add(grid);
const target=new THREE.Vector3(),orbit={yaw:.55,pitch:.3,distance:300},pan=new THREE.Vector2();
const preview=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshBasicMaterial({color:'#78a273',transparent:true,opacity:.2,depthWrite:false}));scene.add(preview);preview.visible=false;
function updateCamera(){const r=$('#viewer').getBoundingClientRect();camera.aspect=r.width/r.height;camera.setViewOffset(r.width,r.height,pan.x,pan.y,r.width,r.height);camera.position.set(target.x+orbit.distance*Math.sin(orbit.yaw)*Math.cos(orbit.pitch),target.y+orbit.distance*Math.sin(orbit.pitch),target.z+orbit.distance*Math.cos(orbit.yaw)*Math.cos(orbit.pitch));camera.lookAt(target);camera.updateProjectionMatrix();camera.updateMatrixWorld();renderer.render(scene,camera);}
function bounds(){const v=state.panels.flatMap(CubeModel.vertices);if(!v.length)return {minX:0,maxX:1,minY:0,maxY:1,minZ:0,maxZ:1};return {minX:Math.min(...v.map(v=>v[0])),maxX:Math.max(...v.map(v=>v[0])),minY:0,maxY:Math.max(...v.map(v=>v[1])),minZ:Math.min(...v.map(v=>v[2])),maxZ:Math.max(...v.map(v=>v[2]))};}
function panelBox(p){const vs=CubeModel.vertices(p),lo=[0,1,2].map(i=>Math.min(...vs.map(v=>v[i]))),hi=[0,1,2].map(i=>Math.max(...vs.map(v=>v[i]))),unit=[state.width,state.height,state.depth];const box=new THREE.Mesh(new THREE.BoxGeometry(...lo.map((v,i)=>Math.max(.6,(hi[i]-v)*unit[i]))),new THREE.MeshBasicMaterial({visible:false}));box.position.set(...lo.map((v,i)=>(v+hi[i])/2*unit[i]));box.userData.cell=p;return box;}
function buildSlots(){dispose(slots);}
function fit(){camera.zoom=1;const b=bounds();let minX=b.minX*state.width,maxX=b.maxX*state.width,minZ=b.minZ*state.depth,maxZ=b.maxZ*state.depth,minY=0,maxY=b.maxY*state.height;if(state.table?.enabled){const t=state.table;minX=Math.min(minX,t.x-t.width/2);maxX=Math.max(maxX,t.x+t.width/2);minZ=Math.min(minZ,t.z-t.depth/2);maxZ=Math.max(maxZ,t.z+t.depth/2);minY=-t.height;}target.set((minX+maxX)/2,(minY+maxY)/2,(minZ+maxZ)/2);const max=Math.max(maxX-minX,maxY-minY,maxZ-minZ);orbit.distance=max*2.4/Math.min(1,camera.aspect);pan.set(0,0);updateCamera();}
function currentTable(){return state.table||{enabled:false,width:180,depth:75,height:74,x:0,z:0};}
function renderTable(){dispose(tableGroup);const t=currentTable();$('#tableEnabled').checked=t.enabled;$('#tableFields').hidden=!t.enabled;for(const [key,id] of Object.entries({width:'tableWidth',depth:'tableDepth',height:'tableHeight',x:'tableX',z:'tableZ'}))$('#'+id).value=t[key];grid.position.y=t.enabled?-t.height-.5:-.5;if(!t.enabled)return;
 function part(w,h,d,x,y,z,color){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));mesh.position.set(x,y,z);tableGroup.add(mesh);}
 part(t.width,3,t.depth,t.x,-1.5,t.z,'#c5aa83');for(const x of [-1,1])for(const z of [-1,1])part(3,t.height-3,3,t.x+x*(t.width/2-8),-(t.height+3)/2,t.z+z*(t.depth/2-6),'#69736c');
 const outside=state.panels.filter(p=>CubeModel.vertices(p).some(v=>v[0]*state.width<t.x-t.width/2-.01||v[0]*state.width>t.x+t.width/2+.01||v[2]*state.depth<t.z-t.depth/2-.01||v[2]*state.depth>t.z+t.depth/2+.01)).length;
 $('#tableFit').textContent=outside?`${outside} panel(s) extend beyond the table footprint. Check placement and support.`:'Display fits within the table footprint.';
}
$('#tableEnabled').onchange=e=>{change(()=>state.table={...currentTable(),enabled:e.target.checked},'Table reference updated.');fit();};
for(const [key,id,min,max] of [['width','tableWidth',30,400],['depth','tableDepth',20,200],['height','tableHeight',30,120],['x','tableX',-1000,1000],['z','tableZ',-1000,1000]])$('#'+id).onchange=e=>{const value=Number(e.target.value);if(!Number.isFinite(value)||value<min||value>max){e.target.value=currentTable()[key];$('#status').textContent=`Choose a value between ${min} and ${max} cm.`;return;}change(()=>state.table={...currentTable(),[key]:value},'Table dimensions updated.');};
document.querySelectorAll('[data-table-edge]').forEach(button=>button.onclick=()=>{const edge=button.dataset.tableEdge,next=CubeModel.alignTable(state,currentTable(),edge);if(Math.abs(next.x)>1000||Math.abs(next.z)>1000){$('#status').textContent='This alignment exceeds the table position range.';return;}change(()=>state.table=next,`Display aligned to the ${edge} table edge.`);});
$('#centerTable').onclick=()=>{const b=bounds();change(()=>state.table={...currentTable(),x:(b.minX+b.maxX)*state.width/2,z:(b.minZ+b.maxZ)*state.depth/2},'Table centred under the display.');};
function dispose(group){while(group.children.length){const o=group.children[0];group.remove(o);o.traverse(n=>{n.geometry?.dispose();if(n.material)for(const m of Array.isArray(n.material)?n.material:[n.material])m.dispose();});}}
function meshPanel(p){const w=state.width,h=state.height,d=state.depth,u=p.u||1,v=p.v||1;let a,b,pos,rot;
 if(p.type==='side'){a=d*u;b=h*v;pos=[p.x*w,(p.y+v/2)*h,(p.z+u/2)*d];rot=[0,Math.PI/2,0];}
 else if(p.type==='shelf'){a=w*u;b=d*v;pos=[(p.x+u/2)*w,p.y*h,(p.z+v/2)*d];rot=[-Math.PI/2,0,0];}
 else{a=w*u;b=h*v;pos=[(p.x+u/2)*w,(p.y+v/2)*h,p.z*d];rot=[0,0,0];}
 const group=new THREE.Group();group.position.set(...pos);group.rotation.set(...rot);
 const frame=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(a,b,.45)),new THREE.LineBasicMaterial({color:p.color}));group.add(frame);
 if(p.material==='plastic')group.add(new THREE.Mesh(new THREE.BoxGeometry(a,b,.35),new THREE.MeshStandardMaterial({color:p.color,roughness:.8})));
 else{const points=[];for(let x=-a/2+3;x<a/2;x+=3)points.push(new THREE.Vector3(x,-b/2,0),new THREE.Vector3(x,b/2,0));for(let y=-b/2+3;y<b/2;y+=3)points.push(new THREE.Vector3(-a/2,y,0),new THREE.Vector3(a/2,y,0));group.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:p.color,transparent:true,opacity:.65})));}
 group.userData.panelKey=CubeModel.panelKey(p);root.add(group);
}
function render(){if(selected===null)multiSelection.clear();const existingKeys=new Set(state.panels.map(CubeModel.panelKey));for(const key of multiSelection)if(!existingKeys.has(key))multiSelection.delete(key);const previous=new Set(root.children.map(o=>o.userData.panelKey));stopAssembly();dispose(root);dispose(hits);CubeModel.panels(state).forEach(meshPanel);animateAssembly(root.children.filter(o=>!previous.has(o.userData.panelKey)));
 for(const p of state.panels){const box=panelBox(p);hits.add(box);if(multiSelection.has(CubeModel.panelKey(p))||CubeModel.panelKey(p)===selected){const outline=new THREE.LineSegments(new THREE.EdgesGeometry(box.geometry),new THREE.LineBasicMaterial({color:'#db922d',depthTest:false}));outline.position.copy(box.position);outline.renderOrder=10;root.add(outline);}}
 buildSlots();buildConnectors();renderTable();
 for(const id of ['name','width','height','depth'])$('#'+id).value=state[id];
 const b=bounds(),inv=CubeModel.inventory(state);$('#count').textContent=inv.full;$('#size').textContent=[(b.maxX-b.minX)*state.width,b.maxY*state.height,(b.maxZ-b.minZ)*state.depth].map(n=>+n.toFixed(1)).join(' × ');$('#panels').textContent=inv.half;$('#connectors').textContent=inv.connectors;
 $('#parts').replaceChildren();for(const row of inv.rows){const tr=document.createElement('tr');for(const text of ['Panel',row.dims.join(' × '),row.material==='mesh'?'Wire mesh':'Solid plastic',row.count]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('#parts').append(tr);}
 $('#checks').textContent='Panels snap edge-to-edge. Check bracing, tabletop support and kit load limits before building.';
 const current=state.panels.find(c=>CubeModel.panelKey(c)===selected);$('#selectedText').textContent=multiSelection.size>1?`${multiSelection.size} panels selected · choose a style, then Apply.`:current?`${current.type==='back'?'Backdrop':current.type==='side'?'Side':'Shelf'} panel · ${current.material}. Shift-click to add more panels.`:'Select a panel to edit it.';$('#apply').disabled=!current;$('#remove').disabled=!current;$('#undo').disabled=!past.length;$('#redo').disabled=!future.length;preview.visible=false;updateCamera();
 try{localStorage.setItem(storageKey,JSON.stringify(state));}catch(e){$('#status').textContent='Browser storage is full. Save a design file to keep these changes.';}
}
function change(fn,message){const before=JSON.stringify(state);fn();if(JSON.stringify(state)===before)return;past.push(before);if(past.length>60)past.shift();future=[];render();$('#status').textContent=message;}
function history(from,to){if(!from.length)return;to.push(JSON.stringify(state));state=JSON.parse(from.pop());selected=null;render();$('#status').textContent='Layout restored.';}
$('#undo').onclick=()=>history(past,future);$('#redo').onclick=()=>history(future,past);
for(const id of ['width','height','depth'])$('#'+id).onchange=e=>{const v=Number(e.target.value);if(!Number.isFinite(v)||v<10||v>100){e.target.value=state[id];$('#status').textContent='Choose a dimension between 10 and 100 cm.';return;}change(()=>state[id]=v,'Cube dimensions updated.');fit();};
$('#name').onchange=e=>change(()=>state.name=e.target.value,'Design renamed.');
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{change(()=>{state.panels=b.dataset.preset==='single'?[]:CubeModel.panels({version:1,cubes:preset(b.dataset.preset),back:true});selected=null;},'New shape ready. Undo restores your previous layout.');fit();});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(n=>n.classList.toggle('active',n===b));$('#tip').textContent=mode==='add'?'Drag a panel edge to extend it':mode==='select'?'Click to select · Shift-click adds panels':mode==='paint'?'Brush across panels to apply the selected style':'Click a panel to remove it · Undo brings it back';preview.visible=false;clearExtension();canvas.style.cursor=mode==='paint'?'crosshair':'grab';buildSlots();updateCamera();});
function remove(key){const removed=state.panels.find(c=>CubeModel.panelKey(c)===key);if(!removed)return;change(()=>{state.panels=state.panels.filter(c=>CubeModel.panelKey(c)!==key);selected=null;},'Panel removed. Undo brings it back.');removalEffect(removed);}
function selectionKeys(){return multiSelection.size?new Set(multiSelection):new Set(selected?[selected]:[]);}
$('#remove').onclick=()=>{const keys=selectionKeys();if(!keys.size)return;change(()=>{state.panels=state.panels.filter(p=>!keys.has(CubeModel.panelKey(p)));selected=null;},`${keys.size} panels removed. Undo restores them.`);};
$('#apply').onclick=()=>{const keys=selectionKeys();change(()=>state.panels.forEach(p=>{if(keys.has(CubeModel.panelKey(p)))Object.assign(p,appearance());}),`Style applied to ${keys.size} panel(s).`);};
function selectGroup(panels){multiSelection.clear();panels.forEach(p=>multiSelection.add(CubeModel.panelKey(p)));selected=multiSelection.values().next().value||null;render();}
$('#selectAll').onclick=()=>selectGroup(state.panels);
$('#selectMatching').onclick=()=>{const p=state.panels.find(p=>CubeModel.panelKey(p)===selected);if(p)selectGroup(state.panels.filter(q=>q.material===p.material&&q.color===p.color));};
$('#clearSelection').onclick=()=>{selected=null;render();};
$('#orientation').onchange=()=>{preview.visible=false;buildSlots();updateCamera();};
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function hit(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);hits.updateMatrixWorld(true);slots.updateMatrixWorld(true);const panelHit=ray.intersectObjects(hits.children)[0];return panelHit;}

const buildCursor='url("data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><path d="M3 2L3 22L9 17L14 27L19 24L14 15L23 15Z" fill="#294f42" stroke="white" stroke-width="2"/><path d="M23 3V11M19 7H27" stroke="#d9992f" stroke-width="3"/></svg>')+'") 3 2, crosshair';
const extensionPreview=new THREE.Group(),connectorGroup=new THREE.Group();scene.add(extensionPreview,connectorGroup);
function world(v){return new THREE.Vector3(v[0]*state.width,v[1]*state.height,v[2]*state.depth);}
function screen(v){const r=canvas.getBoundingClientRect(),p=world(v).project(camera);return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}

function buildConnectors(){dispose(connectorGroup);const corners=new Map();for(const p of state.panels)for(const v of CubeModel.vertices(p))corners.set(v.join(','),v);for(const v of corners.values()){const joint=new THREE.Mesh(new THREE.SphereGeometry(Math.min(state.width,state.height,state.depth)*.045,8,6),new THREE.MeshStandardMaterial({color:'#303a35',roughness:.6}));joint.position.copy(world(v));connectorGroup.add(joint);}}
function edgeDirections(edge){const tangent=edge.ends[0].findIndex((v,i)=>v!==edge.ends[1][i]);return ['x','y','z'].flatMap((axis,i)=>i===tangent?[]:[-1,1].map(sign=>{const out=[...edge.mid];out[i]+=sign;const a=screen(edge.mid),b=screen(out);return {axis,sign,dx:b.x-a.x,dy:b.y-a.y};})).filter(d=>Math.hypot(d.dx,d.dy)>12);}

function edgeAt(e){let best=null;for(const p of state.panels){const v=CubeModel.vertices(p);for(const [i,j] of [[0,1],[0,2],[1,3],[2,3]]){const a=screen(v[i]),b=screen(v[j]),dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((e.clientX-a.x)*dx+(e.clientY-a.y)*dy)/(dx*dx+dy*dy||1))),distance=Math.hypot(e.clientX-a.x-t*dx,e.clientY-a.y-t*dy);if(distance>11||best&&distance>=best.distance)continue;const axes=p.type==='side'?['z','y']:p.type==='shelf'?['x','z']:['x','y'];const axis=axes.find(axis=>v[i][{x:0,y:1,z:2}[axis]]===v[j][{x:0,y:1,z:2}[axis]]),k={x:0,y:1,z:2}[axis],sign=v[i][k]===p[axis]?-1:1,mid=v[i].map((n,k)=>(n+v[j][k])/2),out=[...mid];out[k]+=sign;const start=screen(mid),end=screen(out);if(Math.hypot(end.x-start.x,end.y-start.y)<15)continue;best={p,axis,sign,distance,mid,ends:[v[i],v[j]],dx:end.x-start.x,dy:end.y-start.y};}}return best;}
function clearExtension(){dispose(extensionPreview);}
function showExtension(list,valid){clearExtension();for(const p of list){const box=panelBox(p);box.material.dispose();box.material=new THREE.MeshBasicMaterial({color:valid?'#78a273':'#cc684d',transparent:true,opacity:.35,depthWrite:false});extensionPreview.add(box);const outline=new THREE.LineSegments(new THREE.EdgesGeometry(box.geometry),new THREE.LineBasicMaterial({color:valid?'#e6ac43':'#cf4c35',depthTest:false}));outline.position.copy(box.position);outline.renderOrder=20;extensionPreview.add(outline);for(const v of CubeModel.vertices(p)){const dot=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:valid?'#f4c46c':'#cf4c35'}));dot.position.copy(world(v));extensionPreview.add(dot);}}updateCamera();}
let down=null;const canvas=renderer.domElement;
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{if(down)return;e.preventDefault();const edge=mode==='add'&&e.button===0?edgeAt(e):null;canvas.setPointerCapture(e.pointerId);down={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,button:e.button,moved:false,edge,list:[],valid:false};});
canvas.addEventListener('pointermove',e=>{if(down){if(e.pointerId!==down.id)return;const dx=e.clientX-down.lastX,dy=e.clientY-down.lastY;down.moved ||= Math.hypot(e.clientX-down.x,e.clientY-down.y)>4;if(down.edge){const edge=down.edge,options=edgeDirections(edge),mx=e.clientX-down.x,my=e.clientY-down.y;options.sort((a,b)=>(mx*b.dx+my*b.dy)/Math.hypot(b.dx,b.dy)-(mx*a.dx+my*a.dy)/Math.hypot(a.dx,a.dy));const direction=down.lockedDirection||options[0]||edge,length=(mx*direction.dx+my*direction.dy)/(direction.dx*direction.dx+direction.dy*direction.dy);down.direction=direction;down.erasing=direction.axis===edge.axis&&direction.sign===-edge.sign;down.list=CubeModel.edgeExtension(edge.ends,direction.axis,direction.sign,length).map(p=>({...p,...appearance(),...(e.shiftKey?{material:'plastic'}:{})}));down.valid=state.panels.length+down.list.length<=1500&&down.list.every(p=>p.y>=0&&Math.abs(p.x)<=31&&p.y<=31&&Math.abs(p.z)<=31&&!state.panels.some(q=>CubeModel.overlaps(p,q)));if(down.erasing){down.list=CubeModel.retraction(state.panels,edge.p,edge.axis,edge.sign,length);down.valid=true;}down.mergedPreview=!down.erasing&&down.valid?CubeModel.addAndMerge(state.panels,down.list):null;showExtension(down.mergedPreview?.placed||down.list,down.valid&&!down.erasing);$('#tip').textContent=down.erasing?(down.list.length?`Release to remove ${down.list.length} panel(s) · Undo restores them`:'Drag past the panel centre to remove it'):down.list.length?`${direction.axis.toUpperCase()} direction · ${down.list.length} piece(s) · ${e.shiftKey?'plastic · ':''}${down.valid?(down.mergedPreview?.merged?'release to merge into full panel':'release to build'):'blocked'} · R to turn`:'Pull to build · R changes direction · Shift: plastic';}else if(down.moved){clearExtension();if(down.button===2||e.shiftKey){pan.x-=dx;pan.y-=dy;}else{orbit.yaw-=dx*.008;orbit.pitch=Math.max(-1.2,Math.min(1.45,orbit.pitch+dy*.008));}updateCamera();}down.lastX=e.clientX;down.lastY=e.clientY;return;}if(mode==='add'){const edge=edgeAt(e);clearExtension();if(edge){const points=CubeModel.vertices(edge.p),k={x:0,y:1,z:2}[edge.axis],boundary=edge.p[edge.axis]+(edge.sign>0?(edge.axis===(edge.p.type==='side'?'z':'x')?(edge.p.u||1):(edge.p.v||1)):0),ends=points.filter(v=>v[k]===boundary);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(ends.map(world)),new THREE.LineBasicMaterial({color:'#d9992f',depthTest:false}));extensionPreview.add(line);}canvas.style.cursor=edge?buildCursor:'grab';$('#tip').textContent=edge?'Pull out to build · pull inward to erase · R to turn · Shift: plastic':'Hover a panel edge, then drag to extend';updateCamera();}});
function cancelDrag(){down=null;clearExtension();updateCamera();}
canvas.addEventListener('pointerup',e=>{if(!down||down.id!==e.pointerId)return;const drag=down;down=null;clearExtension();if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(drag.edge){if(drag.valid&&drag.list.length){if(drag.erasing){const keys=new Set(drag.list.map(CubeModel.panelKey));change(()=>{state.panels=state.panels.filter(p=>!keys.has(CubeModel.panelKey(p)));selected=null;},`${keys.size} panel(s) removed. Undo restores the whole drag.`);chime(true);toast(`${keys.size} panel(s) removed · Undo brings them back`);return;}const result=CubeModel.addAndMerge(state.panels,drag.list);change(()=>{state.panels=result.panels;selected=CubeModel.panelKey(result.placed.at(-1));},result.merged?`${result.merged} pair(s) of half panels merged into full panels. Undo restores the previous layout.`:`${drag.list.length} panel piece(s) added. Undo removes the whole extension.`);celebrate(result.placed.at(-1));if(result.merged)toast('Half + half → full panel');}else updateCamera();return;}if(drag.moved||drag.button!==0)return;const h=hit(e);if(!h)return;const p=h.object.userData.cell;if(mode==='remove')remove(CubeModel.panelKey(p));else{const key=CubeModel.panelKey(p);if(e.shiftKey){if(selected)multiSelection.add(selected);if(multiSelection.has(key))multiSelection.delete(key);else multiSelection.add(key);selected=multiSelection.values().next().value||null;}else{multiSelection.clear();multiSelection.add(key);selected=key;}render();}});
canvas.addEventListener('pointercancel',cancelDrag);canvas.addEventListener('lostpointercapture',()=>{if(down)cancelDrag();});window.addEventListener('blur',cancelDrag);window.addEventListener('keydown',e=>{if(e.key==='Escape')cancelDrag();if(e.key.toLowerCase()==='r'&&down?.edge){e.preventDefault();const choices=edgeDirections(down.edge),current=choices.findIndex(d=>d.axis===down.direction?.axis&&d.sign===down.direction?.sign);down.lockedDirection=choices[(current+1)%choices.length];down.direction=down.lockedDirection;down.list=[];down.valid=false;clearExtension();$('#tip').textContent='Direction '+down.direction.axis.toUpperCase()+' · move the mouse to preview';updateCamera();}});canvas.addEventListener('pointerleave',()=>{if(!down){clearExtension();updateCamera();}});canvas.addEventListener('wheel',e=>{e.preventDefault();if(down?.edge)return;camera.zoom=Math.max(.15,Math.min(8,camera.zoom*Math.exp(-e.deltaY*.001)));updateCamera();},{passive:false});
$('#startPanel').onclick=()=>{const p={type:$('#orientation').value,x:0,y:0,z:0,...appearance()};if(state.panels.some(q=>CubeModel.overlaps(p,q))){$('#status').textContent='A panel already occupies that starting plane. Extend an existing edge.';return;}change(()=>state.panels.push(p),'Starter panel added. Drag an edge to extend it.');fit();};
$('#fit').onclick=fit;$('#front').onclick=()=>{orbit.yaw=0;orbit.pitch=0;fit();};
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#save').onclick=()=>download((state.name.replace(/[^a-z0-9_-]/gi,'-')||'cube-layout')+'.json',JSON.stringify(state,null,2),'application/json');$('#open').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20e6)throw Error('Choose a design file smaller than 20 MB.');const next=CubeModel.migrate(JSON.parse(await file.text()));change(()=>{state=next;selected=null;},'Design opened.');fit();}catch(error){$('#status').textContent=error.message;}e.target.value='';};
$('#csv').onclick=()=>{const inv=CubeModel.inventory(state);const rows=[['Part','Long edge cm','Short edge cm','Material','Quantity'],...inv.rows.map(r=>['Panel',...r.dims,r.material==='mesh'?'Wire mesh':'Solid plastic',r.count]),['Connector positions','','','',inv.connectors]];download('cube-parts.csv',rows.map(r=>r.join(',')).join('\r\n'),'text/csv');};
window.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?history(future,past):history(past,future);}if(e.key==='Delete'&&selected)$('#remove').click();});

// Animation only affects presentation; the layout and inventory update immediately.
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
let calm=reducedMotion.matches,soundEnabled=false,audioContext=null,assemblyFrame=0,assemblyItems=[],toastTimer=0;
function syncCalm(){document.body.classList.toggle('calm',calm);$('#motion').setAttribute('aria-pressed',String(calm));$('#motion').textContent=calm?'Calm mode on':'Calm mode';}
syncCalm();$('#motion').onclick=()=>{calm=!calm;syncCalm();if(calm){stopAssembly();updateCamera();}};
reducedMotion.addEventListener('change',e=>{calm=e.matches;syncCalm();if(calm){stopAssembly();updateCamera();}});
$('#sound').onclick=()=>{soundEnabled=!soundEnabled;$('#sound').setAttribute('aria-pressed',String(soundEnabled));$('#sound').textContent=soundEnabled?'Sound on':'Sound off';if(soundEnabled)chime(false);};
function chime(remove){if(!soundEnabled)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const t=audioContext.currentTime;for(let i=0;i<2;i++){const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(remove?330-i*80:520+i*260,t+i*.055);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.035,t+i*.055+.008);gain.gain.exponentialRampToValueAtTime(.001,t+i*.055+.18);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(t+i*.055);oscillator.stop(t+i*.055+.2);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}}catch(e){soundEnabled=false;$('#sound').textContent='Sound unavailable';$('#sound').setAttribute('aria-pressed','false');}}
function stopAssembly(){cancelAnimationFrame(assemblyFrame);for(const item of assemblyItems){item.object.scale.setScalar(1);item.object.position.copy(item.position);}assemblyItems=[];}
function animateAssembly(objects){if(calm||reducedMotion.matches||!objects.length)return;assemblyItems=objects.map((object,i)=>({object,position:object.position.clone(),delay:Math.min(i*22,180)}));const start=performance.now();function frame(now){let running=false;for(const item of assemblyItems){const t=Math.max(0,Math.min(1,(now-start-item.delay)/500));const spring=t===1?1:1-Math.exp(-7*t)*Math.cos(10*t);item.object.scale.setScalar(Math.max(.05,spring));item.object.position.copy(item.position);item.object.position.y+=(1-t)*(1-t)*state.height*.35;if(t<1)running=true;}renderer.render(scene,camera);if(running)assemblyFrame=requestAnimationFrame(frame);else{assemblyItems=[];assemblyFrame=0;}}assemblyFrame=requestAnimationFrame(frame);}
function toast(message){clearTimeout(toastTimer);const el=$('#buildToast');el.textContent=message;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),1800);}
function celebrate(c){chime(false);}
function removalEffect(c){chime(true);toast('Panel removed · Undo brings it back');if(calm||reducedMotion.matches)return;const ghost=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(c.type==='side'?.6:state.width,c.type==='shelf'?.6:state.height,c.type==='back'?.6:state.depth)),new THREE.LineBasicMaterial({color:'#c77a50',transparent:true,opacity:.85}));ghost.position.set((c.x+(c.type==='side'?0:.5))*state.width,(c.y+(c.type==='shelf'?0:.5))*state.height,(c.z+(c.type==='back'?0:.5))*state.depth);scene.add(ghost);const start=performance.now();function frame(now){const t=Math.min(1,(now-start)/320);ghost.scale.setScalar(1-t*.85);ghost.material.opacity=(1-t)*.85;renderer.render(scene,camera);if(t<1&&!calm&&!reducedMotion.matches)requestAnimationFrame(frame);else{scene.remove(ghost);ghost.geometry.dispose();ghost.material.dispose();renderer.render(scene,camera);}}requestAnimationFrame(frame);}


const colours=[['Sage','#53695e'],['Charcoal','#303a35'],['White','#f3f0e6'],['Sand','#c5aa83'],['Rose','#cb919a'],['Lavender','#a79bc2']];
for(const [name,color] of colours){const button=document.createElement('button');button.style.setProperty('--swatch',color);button.setAttribute('aria-label',name);button.title=name;button.dataset.color=color;button.onclick=()=>{$('#color').value=color;syncStyle();};$('.swatches').append(button);}
function syncStyle(){const style=appearance();document.querySelectorAll('[data-material]').forEach(b=>{const chosen=b.dataset.material===style.material;b.classList.toggle('chosen',chosen);b.setAttribute('aria-pressed',String(chosen));});document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===style.color)));document.documentElement.style.setProperty('--paint',style.color);$('#styleSummary').textContent=`${colours.find(c=>c[1]===style.color)?.[0]||style.color} · ${style.material==='mesh'?'Wire mesh':'Solid plastic'}`;}
document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>{$('#material').value=b.dataset.material;syncStyle();});$('#color').oninput=syncStyle;syncStyle();
let paintStroke=null;
function brush(e){const h=hit(e);if(!h)return;const p=h.object.userData.cell,key=CubeModel.panelKey(p);if(paintStroke.keys.has(key))return;paintStroke.keys.add(key);const group=root.children.find(o=>o.userData.panelKey===key);group?.traverse(o=>{if(o.material?.color)o.material.color.set(paintStroke.style.color);});renderer.render(scene,camera);$('#tip').textContent=`Painting ${paintStroke.keys.size} panel(s) · release to apply · Esc cancels`;}
function finishPaint(cancel=false){const stroke=paintStroke;if(!stroke)return;paintStroke=null;if(canvas.hasPointerCapture(stroke.id))canvas.releasePointerCapture(stroke.id);if(cancel){render();return;}change(()=>state.panels.forEach(p=>{if(stroke.keys.has(CubeModel.panelKey(p)))Object.assign(p,stroke.style);}),`Painted ${stroke.keys.size} panel(s). Undo restores the whole stroke.`);render();}
canvas.addEventListener('pointerdown',e=>{if(mode!=='paint'||e.button!==0||!hit(e))return;e.preventDefault();e.stopImmediatePropagation();paintStroke={id:e.pointerId,keys:new Set(),style:appearance()};canvas.setPointerCapture(e.pointerId);brush(e);},true);
canvas.addEventListener('pointermove',e=>{if(!paintStroke||e.pointerId!==paintStroke.id)return;e.stopImmediatePropagation();brush(e);},true);
canvas.addEventListener('pointerup',e=>{if(!paintStroke||e.pointerId!==paintStroke.id)return;e.stopImmediatePropagation();finishPaint();},true);
canvas.addEventListener('pointercancel',()=>finishPaint(true));canvas.addEventListener('lostpointercapture',()=>finishPaint(true));window.addEventListener('blur',()=>finishPaint(true));window.addEventListener('keydown',e=>{if(!paintStroke)return;if(e.key==='Escape'||((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')){e.preventDefault();e.stopImmediatePropagation();finishPaint(true);}},true);

new ResizeObserver(()=>{const r=$('#viewer').getBoundingClientRect();renderer.setSize(r.width,r.height);updateCamera();}).observe($('#viewer'));render();fit();

// Kit presets change all grid dimensions in one undoable edit.
document.querySelectorAll('[data-grid-size]').forEach(button=>button.onclick=()=>{change(()=>{state.width=Number(button.dataset.gridSize);state.height=30;state.depth=30;},'Kit dimensions updated. Undo restores the previous size.');fit();});
