(()=>{
$('#selection').insertAdjacentHTML('beforeend',`<h2>Move a section</h2><p>Select panels, then drag them in Move mode. Empty space rotates the view.</p><label class="check"><input id="moveCopy" type="checkbox"> Duplicate while moving</label><label class="check"><input id="edgeSnap" type="checkbox" checked> Snap to table edges</label><label>Table inset · cm<input id="tableInset" type="number" min="0" max="20" value="0"></label><div class="presets"><button id="sectionUp">Raise ½ panel</button><button id="sectionDown">Lower ½ panel</button></div>`);
$('.modes').insertAdjacentHTML('beforeend','<button id="moveMode">↔ Move</button><button id="productMode">▣ Products</button>');
const productsPanel=document.createElement('details');productsPanel.className='productTools';productsPanel.innerHTML=`<summary>Products, prints & signs</summary><p>Dimensions are cm. Drag items onto grid panels to snap to the surface. Base height controls free placement.</p><select id="boothProduct"><option value="">New product</option></select><label>Item type<select id="bpKind"><option value="product">Product / sign</option><option value="hook">Metal display hook</option><option value="acrylic">Tiered acrylic stand</option></select></label><label>Acrylic levels<input id="bpLevels" type="number" min="1" max="8" value="3"></label><button id="openStandEditor">Open display-stand editor</button><label>Name<input id="bpName" value="Art print"></label><div class="dimensions"><label>Width<input id="bpWidth" type="number" min=".1" max="300" value="21"></label><label>Height<input id="bpHeight" type="number" min=".1" max="300" value="29.7"></label><label>Depth<input id="bpDepth" type="number" min=".1" max="300" value=".3"></label></div><label>Base height above tabletop<input id="bpY" type="number" min="0" max="1500" value="0"></label><label>Artwork (PNG, JPEG, WebP)<input id="bpImage" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="presets"><button id="bpAdd">Add copy</button><button id="bpUpdate">Update selected</button><button id="bpDelete">Remove selected</button><button id="bpExport">Export products</button><button id="bpImport">Import products</button></div><input id="bpFile" type="file" accept=".json" hidden>`;$('#section-build').prepend(productsPanel);
$('.parts>div').insertAdjacentHTML('beforeend','<button id="printPlan">Print setup sheet</button>');
let pendingMeshColors=null,pendingMesh=null,activeProduct=null,pendingImage='',moveDrag=null;const productGroup=new THREE.Group();scene.add(productGroup);
const itemTrash=document.createElement('div');itemTrash.className='itemTrash';itemTrash.hidden=true;itemTrash.setAttribute('role','status');itemTrash.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/></svg><span>Drop to remove</span>';$('#viewer').append(itemTrash);
function showTrash(show){itemTrash.hidden=!show;itemTrash.classList.remove('over');}
function overTrash(e){const r=itemTrash.getBoundingClientRect(),over=!itemTrash.hidden&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;itemTrash.classList.toggle('over',over);return over;}
function removeItem(id){change(()=>{state.products=BoothModel.removeProduct(state.products||[],id);},'Item removed. Undo to restore.');if(activeProduct===id)activeProduct=null;}
function switchMode(next){mode=next;document.querySelectorAll('.modes button').forEach(b=>b.classList.toggle('active',b.id===(next==='move'?'moveMode':'productMode')));clearExtension();$('#tip').textContent=next==='move'?'Drag selected panels · table edges snap · Esc cancels':'Drag onto a grid panel to snap to its surface';if(next==='product'){document.querySelector('[data-section="build"]').click();}updateCamera();}
$('#moveMode').onclick=()=>switchMode('move');$('#productMode').onclick=()=>switchMode('product');document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{$('#moveMode').classList.remove('active');$('#productMode').classList.remove('active');}));
function syncProducts(){const chosen=$('#boothProduct').value;$('#boothProduct').replaceChildren(new Option('New product',''));for(const p of state.products||[])$('#boothProduct').add(new Option(p.name,p.id));$('#boothProduct').value=(state.products||[]).some(p=>p.id===chosen)?chosen:'';$('#bpUpdate').disabled=!$('#boothProduct').value;$('#bpDelete').disabled=!$('#boothProduct').value;
 productGroup.traverse(o=>o.material?.map?.dispose());dispose(productGroup);for(const p of state.products||[]){const group=new THREE.Group();group.userData.productId=p.id;group.position.set(p.x,p.y+p.height/2,p.z);group.rotation.order='YXZ';group.rotation.set(p.tilt||0,p.rotation||0,0);if(p.kind&&p.kind!=='product'){AccessoryViews.build(group,p);if(p.kind==='hook'){const grab=new THREE.Mesh(new THREE.BoxGeometry(Math.max(6,p.width+3),Math.max(6,p.height+3),p.depth+3),new THREE.MeshBasicMaterial({visible:false}));grab.userData.hookGrab=true;group.add(grab);if(p.id===activeProduct)group.traverse(o=>{if(o.material?.emissive){o.material.emissive.set('#b17a25');o.material.emissiveIntensity=.35;}});}productGroup.add(group);continue;}const box=new THREE.Mesh(new THREE.BoxGeometry(p.width,p.height,p.depth),new THREE.MeshStandardMaterial({color:p.id===activeProduct?'#e2be7e':'#eee3cf',roughness:.8}));group.add(box);if(p.image){const tex=new THREE.TextureLoader().load(p.image,loaded=>{const ratio=loaded.image.width/loaded.image.height;face.scale.set(Math.min(1,p.height*ratio/p.width),Math.min(1,p.width/ratio/p.height),1);renderer.render(scene,camera);});tex.colorSpace=THREE.SRGBColorSpace;const face=new THREE.Mesh(new THREE.PlaneGeometry(p.width,p.height),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}));face.position.z=p.depth/2+.03;group.add(face);}productGroup.add(group);}renderer.render(scene,camera);}
const baseRender=render;render=function(){baseRender();syncProducts();refreshItemPalette();};
function loadProduct(p){activeProduct=p?.id||null;pendingMesh=p?.mesh||null;pendingMeshColors=p?.meshColors||null;if(p){$('#bpKind').value=p.kind==='stand'?'product':p.kind||'product';$('#bpLevels').value=p.levels||3;}pendingImage=p?.image||'';if(p)for(const [key,id] of Object.entries({name:'bpName',width:'bpWidth',height:'bpHeight',depth:'bpDepth',y:'bpY'}))$('#'+id).value=p[key];syncProducts();}
$('#boothProduct').onchange=()=>loadProduct((state.products||[]).find(p=>p.id===$('#boothProduct').value));
$('#bpImage').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2000000){$('#status').textContent='Choose an image below 2 MB.';return;}const data=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file);});if(!/^data:image\/(png|jpeg|webp);base64,/.test(data)){$('#status').textContent='Choose PNG, JPEG or WebP.';return;}pendingImage=data;$('#status').textContent='Artwork ready. Add or update the product to apply.';};
function formProduct(id){const old=(state.products||[]).find(p=>p.id===id),p={...(old?.hookId?{hookId:old.hookId,hookOffset:old.hookOffset}:{}),id:id||crypto.randomUUID(),name:$('#bpName').value,width:+$('#bpWidth').value,height:+$('#bpHeight').value,depth:+$('#bpDepth').value,y:+$('#bpY').value,x:old?.x??(state.table?.x||0),z:old?.z??(state.table?.z||0),image:pendingImage,kind:pendingMesh?'stand':$('#bpKind').value,levels:+$('#bpLevels').value,rotation:old?.rotation||0,tilt:old?.tilt||0,...(old?.trayStandId?{trayStandId:old.trayStandId,trayPlane:old.trayPlane}:{}),...(pendingMesh?{mesh:pendingMesh,...(pendingMeshColors?{meshColors:pendingMeshColors}:{})}:{})};return BoothModel.validateProducts([p])[0];}
function saveProduct(copy){try{const p=formProduct(copy?null:$('#boothProduct').value);if(!copy&&!$('#boothProduct').value)return;BoothModel.validateProducts(copy?[...(state.products||[]),p]:(state.products||[]).map(q=>q.id===p.id?p:q));change(()=>{state.products=copy?[...(state.products||[]),p]:BoothModel.moveProduct(state.products,p.id,p);},'Product saved.');$('#boothProduct').value=p.id;loadProduct(p);switchMode('product');}catch(e){$('#status').textContent=e.message;}}
$('#bpAdd').onclick=()=>{if((state.products||[]).length>=200){$('#status').textContent='Maximum 200 products.';return;}saveProduct(true);};$('#bpUpdate').onclick=()=>saveProduct(false);$('#bpDelete').onclick=()=>{const id=$('#boothProduct').value;change(()=>{state.products=(state.products||[]).filter(p=>p.id!==id).map(p=>{if(p.hookId===id){p={...p};delete p.hookId;delete p.hookOffset;}return p;});},'Product removed.');};
$('#bpExport').onclick=()=>download('booth-products.json',JSON.stringify({schema:'booth-products',products:state.products||[]},null,2),'application/json');$('#bpImport').onclick=()=>$('#bpFile').click();$('#bpFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20000000)throw Error('File exceeds 20 MB');const raw=JSON.parse(await f.text());if(raw.schema!=='booth-products')throw Error('Choose a booth-products JSON file');const imported=BoothModel.validateProducts(raw.products),ids=new Map(imported.map(p=>[p.id,crypto.randomUUID()]));const ps=imported.map(p=>{const q={...p,id:ids.get(p.id)};if(q.trayStandId){if(ids.has(q.trayStandId))q.trayStandId=ids.get(q.trayStandId);else{delete q.trayStandId;delete q.trayPlane;}}if(q.hookId){if(ids.has(q.hookId))q.hookId=ids.get(q.hookId);else{delete q.hookId;delete q.hookOffset;}}return q;});if(ps.length+(state.products||[]).length>200)throw Error('Maximum 200 products');BoothModel.validateProducts([...(state.products||[]),...ps]);change(()=>state.products=[...(state.products||[]),...ps],'Products imported.');}catch(error){$('#status').textContent=error.message;}e.target.value='';};
function pickProduct(){productGroup.updateMatrixWorld(true);const matches=ray.intersectObjects(productGroup.children,true);return matches.find(h=>!h.object.userData.hookGrab)||matches[0];}
canvas.addEventListener('pointermove',e=>{if(mode!=='product'||moveDrag||cardDrag)return;hit(e);canvas.style.cursor=pickProduct()?'grab':'';});
function standTarget(p){
 if(p.kind&&p.kind!=='product')return null;
 productGroup.updateMatrixWorld(true);
 const stands=productGroup.children.filter(o=>(state.products||[]).some(q=>q.id===o.userData.productId&&['acrylic','stand'].includes(q.kind)));
 const candidates=ray.intersectObjects(stands,true);
 for(const h of candidates){
  if(!h.face||!h.object.isMesh)continue;
  const normal=h.face.normal.clone().transformDirection(h.object.matrixWorld);
  let group=h.object;while(!group.userData.productId)group=group.parent;
  const stand=state.products.find(q=>q.id===group.userData.productId);
  if(normal.y<.35)continue;
  if(stand.kind==='acrylic'&&!h.object.userData.shelfSurface)continue;
  const local=h.object.worldToLocal(h.point.clone()),geo=h.object.geometry;if(!geo.boundingBox)geo.computeBoundingBox();
  let minX=geo.boundingBox.min.x,maxX=geo.boundingBox.max.x,minZ=geo.boundingBox.min.z,maxZ=geo.boundingBox.max.z;
  const cache=geo.userData.trayBounds||(geo.userData.trayBounds=new Map()),key=[h.face.normal.x.toFixed(3),h.face.normal.y.toFixed(3),h.face.normal.z.toFixed(3),h.face.normal.dot(local).toFixed(2),p.height].join(':'),cached=cache.get(key);
  if(cached){({minX,maxX,minZ,maxZ}=cached);}
  if(stand.kind==='stand'&&!cached){
   // Collect faces on the hit tray plane, including inclined tray floors.
   const a=geo.attributes.position,plane=new THREE.Plane().setFromNormalAndCoplanarPoint(h.face.normal,local),vertex=new THREE.Vector3();minX=minZ=Infinity;maxX=maxZ=-Infinity;
   for(let i=0;i<a.count;i+=3){if([0,1,2].some(j=>Math.abs(plane.distanceToPoint(vertex.fromBufferAttribute(a,i+j)))>.03))continue;
    for(let j=0;j<3;j++){minX=Math.min(minX,a.getX(i+j));maxX=Math.max(maxX,a.getX(i+j));minZ=Math.min(minZ,a.getZ(i+j));maxZ=Math.max(maxZ,a.getZ(i+j));}
   }
  }
  if(stand.kind==='stand'&&!cached){
   // Floors extend through the inset side walls: use their inner faces, not floor ends.
   const a=geo.attributes.position,mid=(minX+maxX)/2,span=maxX-minX;
   let left=minX,right=maxX;
   for(let i=0;i<a.count;i+=3){
    const xs=[0,1,2].map(j=>a.getX(i+j)),ys=[0,1,2].map(j=>a.getY(i+j)),zs=[0,1,2].map(j=>a.getZ(i+j));
    if(Math.max(...xs)-Math.min(...xs)>.01||Math.max(...ys)-Math.min(...ys)<.2)continue;
    if(Math.max(...zs)<minZ||Math.min(...zs)>maxZ||Math.max(...ys)<local.y-.1||Math.min(...ys)>local.y+p.height)continue;
    const x=xs[0];if(x<mid-span*.2)left=Math.max(left,x);else if(x>mid+span*.2)right=Math.min(right,x);
   }
   minX=left;maxX=right;cache.set(key,{minX,maxX,minZ,maxZ});
  }
  const tilt=stand.kind==='stand'?Math.atan2(h.face.normal.z,h.face.normal.y):0,depth=p.depth*Math.cos(tilt),margin=.15;
  if(maxX-minX<p.width+2*margin||maxZ-minZ<depth+2*margin)continue;
  const original=local.clone(),centerX=(minX+maxX)/2,cos=Math.cos(tilt),planeId=h.face.normal.dot(original);
  // Reuse the editor's millimetre-based tray solver, converting from booth centimetres.
  const G={model:{sideX:(maxX-minX)*5},thick:1},tray={t:{depth:(maxZ-minZ)/cos*10}};
  const definition=q=>({id:q.id||'dragged',width:q.width*10,depth:q.depth*10,gap:2});
  const others=[],products=[];
  for(const q of state.products||[]){if(q.id===p.id||q.trayStandId!==stand.id||Math.abs((q.trayPlane||0)-planeId)>.1)continue;
   const at=h.object.worldToLocal(new THREE.Vector3(q.x,q.y+q.height/2,q.z));at.z-=Math.sin(q.tilt||0)*q.height/2;
   others.push({id:q.id,productId:q.id,x:(at.x-centerX)*10,z:(at.z-minZ)/cos*10});products.push(definition(q));
  }
  const placed=ProductPlacement.candidate(G,tray,definition(p),{x:(local.x-centerX)*10,z:1+p.depth*5},others,products,p.id,1,true);
  if(placed.reason)return {invalid:true,reason:placed.reason};
  local.x=centerX+placed.x/10;local.z=minZ+placed.z/10*cos;
  const n=h.face.normal;local.y=original.y-(n.x*(local.x-original.x)+n.z*(local.z-original.z))/n.y;
  const plane=n.dot(original);local.y+=Math.cos(tilt)*p.height/2;local.z+=Math.sin(tilt)*p.height/2;
  const point=h.object.localToWorld(local);return {x:point.x,y:point.y-p.height/2+.04,z:point.z,rotation:stand.rotation||0,tilt:tilt,trayStandId:stand.id,trayPlane:plane};

 }
 return null;
}
function standBoundary(p){
 if(p.kind&&p.kind!=='product')return false;
 productGroup.updateMatrixWorld(true);
 const stands=productGroup.children.filter(o=>(state.products||[]).some(q=>q.id===o.userData.productId&&q.kind==='stand'));
 return ray.intersectObjects(stands,true).some(h=>h.object.isMesh);
}
function accessoryTarget(e,p){
 // Target small accessories directly; the shifted ray remains the floor-placement ray.
 const saved=ray.ray.clone();
 try{hit(e);const hook=hookTarget(p);if(hook)return {hook,tier:null};
 ray.ray.copy(saved);return {hook:null,tier:standTarget(p)};
 }finally{ray.ray.copy(saved);}
}
function hookTarget(p){if(p.kind&&p.kind!=='product')return null;productGroup.updateMatrixWorld(true);const hooks=productGroup.children.filter(o=>(state.products||[]).some(q=>q.id===o.userData.productId&&q.kind==='hook'));const h=ray.intersectObjects(hooks,true)[0];if(!h)return null;let group=h.object;while(!group.userData.productId)group=group.parent;const hook=state.products.find(q=>q.id===group.userData.productId),local=group.worldToLocal(h.point.clone()),offset=Math.max(-hook.depth/2+.5,Math.min(hook.depth/2-.5,local.z));return BoothModel.hang(p,hook,offset);}
// Let normal camera gestures finish; intercept only Remove clicks on items.
canvas.addEventListener('pointerup',e=>{
 if(mode!=='remove'||!down||down.id!==e.pointerId||down.moved||down.button!==0)return;
 const panel=hit(e),product=pickProduct();
 if(!product||(panel&&panel.distance<product.distance))return;
 let object=product.object;while(!object.userData.productId)object=object.parent;
 e.preventDefault();e.stopImmediatePropagation();down=null;clearExtension();
 if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);
 removeItem(object.userData.productId);chime(true);updateCamera();
},true);
function productPointer(e,p,position){return {clientX:e.clientX,clientY:e.clientY,product:p,position};}
function offsetProductRay(e){const p=e.product;if(!p||(p.kind&&p.kind!=='product'))return;const up=new THREE.Vector3(0,p.height,0).applyEuler(new THREE.Euler(e.position?.tilt||0,e.position?.rotation||0,0,'YXZ'));ray.ray.origin.sub(up);}
function placementSurface(e){
 let panel=hit(e);if(e.product){offsetProductRay(e);panel=ray.intersectObjects(hits.children,true)[0]||null;}
 tableGroup.updateMatrixWorld(true);
 const tabletop=state.table?.enabled?ray.intersectObjects(tableGroup.children,true).find(h=>h.face&&h.face.normal.clone().transformDirection(h.object.matrixWorld).y>.95):null;
 if(tabletop&&(!panel||tabletop.distance<panel.distance))return {...tabletop,object:{userData:{cell:{type:'shelf'},tabletop:true}}};
 if(panel&&e.product&&(!e.product.kind||e.product.kind==='product')&&panel.object.userData.cell.type!=='shelf')panel={...panel,point:panel.point.clone().add(new THREE.Vector3(0,e.product.height/2,0))};
 return panel;
}
function groundPoint(e,y){hit(e);offsetProductRay(e);return ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-y),new THREE.Vector3());}
function commitMove(result){if(result.error){$('#status').textContent=result.error;return;}change(()=>{state.panels=result.panels;multiSelection.clear();result.moved.forEach(p=>multiSelection.add(CubeModel.panelKey(p)));selected=multiSelection.values().next().value||null;},'Section moved. Undo restores the whole section.');}
for(const [id,dy] of [['sectionUp',.5],['sectionDown',-.5]])$('#'+id).onclick=()=>commitMove(BoothModel.move(state.panels,selectionKeys(),{x:0,y:dy,z:0},$('#moveCopy').checked));
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||!['move','product'].includes(mode))return;let p,keys;if(mode==='product'){hit(e);const h=pickProduct();if(!h)return;let o=h.object;while(!o.userData.productId)o=o.parent;p=(state.products||[]).find(p=>p.id===o.userData.productId);activeProduct=p.id;$('#boothProduct').value=p.id;loadProduct(p);}else{const h=hit(e);if(!h)return;keys=selectionKeys();if(!keys.has(CubeModel.panelKey(h.object.userData.cell))){selectGroup([h.object.userData.cell]);keys=selectionKeys();}}
 const start=groundPoint(e,p?.y||0);if(!start)return;e.preventDefault();e.stopImmediatePropagation();canvas.style.cursor='grabbing';moveDrag={id:e.pointerId,start,p,keys,copy:$('#moveCopy').checked,result:null};if(p)showTrash(true);canvas.setPointerCapture(e.pointerId);},true);
canvas.addEventListener('pointermove',e=>{if(!moveDrag||moveDrag.id!==e.pointerId)return;e.stopImmediatePropagation();const d=moveDrag,placementPointer=productPointer(e,d.p,d.position||d.p),point=groundPoint(placementPointer,d.p?.y||0);if(d.p){d.trash=overTrash(e);if(d.trash){$('#tip').textContent='Release to remove · Undo restores the item';return;}const surface=placementSurface(placementPointer);const {tier,hook}=accessoryTarget(e,d.p);d.position=hook||tier||(surface?AccessoryViews.snap(d.p,surface):point?{x:point.x,y:d.p.y,z:point.z,rotation:d.p.rotation||0}:null);if(['acrylic','stand'].includes(d.p.kind)&&surface?.object.userData.cell.type!=='shelf'&&point)d.position={x:point.x,y:d.p.y,z:point.z,rotation:d.p.rotation||0};d.position=BoothModel.snapStand(state,d.p,d.position);if(d.position?.invalid){$('#tip').textContent=d.position.reason;d.position=null;return;}if(!d.position)return;$('#tip').textContent=tier?'Snapped to stand shelf':d.position.hookId?'Attached to hook':surface?(surface.object.userData.tabletop?'Snapped to tabletop':'Snapped to '+surface.object.userData.cell.type+' panel'):'Move over a grid panel to snap, or release at the current height';const o=productGroup.children.find(o=>o.userData.productId===d.p.id);o.position.x=d.position.x;o.position.z=d.position.z;o.position.y=d.position.y+d.p.height/2;o.rotation.order='YXZ';o.rotation.set(d.position.tilt||0,d.position.rotation||0,0);if(['hook','stand','acrylic'].includes(d.p.kind)){for(const item of BoothModel.moveProduct(state.products,d.p.id,d.position)){if(item.hookId!==d.p.id&&item.trayStandId!==d.p.id)continue;const child=productGroup.children.find(q=>q.userData.productId===item.id);child.position.set(item.x,item.y+item.height/2,item.z);child.rotation.y=item.rotation||0;}}renderer.render(scene,camera);return;}if(!point)return;let delta={x:Math.round((point.x-d.start.x)/state.width*2)/2,y:0,z:Math.round((point.z-d.start.z)/state.depth*2)/2};const chosen=state.panels.filter(p=>d.keys.has(CubeModel.panelKey(p))),snapped=$('#edgeSnap').checked?BoothModel.snap(state,chosen,{x:(point.x-d.start.x)/state.width,y:0,z:(point.z-d.start.z)/state.depth},Math.max(0,Math.min(20,+$('#tableInset').value||0))):{delta,label:''};if(!snapped.label)snapped.delta=delta;d.result=BoothModel.move(state.panels,d.keys,snapped.delta,d.copy);showExtension(d.result.moved||chosen,!d.result.error);$('#tip').textContent=d.result.error||snapped.label||'Release to move section · half-grid snap';},true);
function finishMove(cancel=false){const d=moveDrag;if(!d)return;moveDrag=null;canvas.style.cursor='';if(canvas.hasPointerCapture(d.id))canvas.releasePointerCapture(d.id);clearExtension();showTrash(false);if(!cancel){if(d.p&&d.trash){removeItem(d.p.id);}else if(d.p&&d.position){if(Math.abs(d.position.x)>1500||Math.abs(d.position.z)>1500){$('#status').textContent='Outside the product area';}else change(()=>state.products=BoothModel.moveProduct(state.products,d.p.id,d.position),'Product moved.');}else if(d.result)commitMove(d.result);}syncProducts();updateCamera();}
canvas.addEventListener('pointerup',e=>{if(moveDrag?.id===e.pointerId){e.stopImmediatePropagation();if(moveDrag.p)moveDrag.trash=overTrash(e);finishMove();}},true);canvas.addEventListener('pointercancel',()=>finishMove(true));canvas.addEventListener('lostpointercapture',()=>finishMove(true));window.addEventListener('blur',()=>finishMove(true));window.addEventListener('keydown',e=>{if(moveDrag&&(e.key==='Escape'||((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'))){e.preventDefault();e.stopImmediatePropagation();finishMove(true);}},true);
// Compact vector views keep the setup sheet crisp when printed or saved as PDF.
function planSVG(top){const lines=state.panels.map((p,i)=>{const v=CubeModel.vertices(p),coords=v.map(v=>[v[0]*state.width,top?v[2]*state.depth:-v[1]*state.height]);return {coords,i};}),points=lines.flatMap(l=>l.coords);for(const p of state.products||[])points.push([p.x-p.width/2,top?p.z-p.depth/2:-p.y-p.height],[p.x+p.width/2,top?p.z+p.depth/2:-p.y]);if(state.table?.enabled){const t=state.table;points.push([t.x-t.width/2,top?t.z-t.depth/2:0],[t.x+t.width/2,top?t.z+t.depth/2:t.height]);}if(!points.length)points.push([0,0],[30,30]);const minX=Math.min(...points.map(p=>p[0]))-10,minY=Math.min(...points.map(p=>p[1]))-10,w=Math.max(...points.map(p=>p[0]))-minX+10,h=Math.max(...points.map(p=>p[1]))-minY+10;let content='';if(state.table?.enabled){const t=state.table;content+=`<rect x="${t.x-t.width/2}" y="${top?t.z-t.depth/2:0}" width="${t.width}" height="${top?t.depth:3}" fill="#eee3cf" stroke="#999"/>`;}for(const p of state.products||[])content+=`<rect x="${p.x-p.width/2}" y="${top?p.z-p.depth/2:-p.y-p.height}" width="${p.width}" height="${top?p.depth:p.height}" fill="#f1d7a4" fill-opacity=".6" stroke="#a8752e" stroke-width=".5"/>`;for(const l of lines){const c=l.coords;content+=`<path d="M${c[0]} L${c[1]} L${c[3]} L${c[2]} Z" fill="none" stroke="#365344" stroke-width=".6"/><text x="${(c[0][0]+c[3][0])/2}" y="${(c[0][1]+c[3][1])/2}" font-size="4">${l.i+1}</text>`;}return `<svg viewBox="${minX} ${minY} ${w} ${h}">${content}</svg>`;}
$('#printPlan').onclick=()=>{let sheet=$('#printSheet');if(!sheet){sheet=document.createElement('section');sheet.id='printSheet';document.body.append(sheet);}sheet.replaceChildren();const title=document.createElement('h1');title.textContent=state.name;sheet.append(title);const info=document.createElement('p'),inv=CubeModel.inventory(state);info.textContent=`${inv.full} full panels · ${inv.half} half panels · ${inv.connectors} connector positions. Dimensions in cm.`;sheet.append(info);const views=document.createElement('div');views.className='printViews';views.innerHTML='<div><h2>Front view</h2>'+planSVG(false)+'</div><div><h2>Top view</h2>'+planSVG(true)+'</div>';sheet.append(views);const table=document.createElement('table');table.innerHTML='<thead><tr><th>#</th><th>Panel</th><th>Size · cm</th><th>Material / colour</th></tr></thead>';for(const [i,p] of state.panels.entries()){const row=table.insertRow(),dims=p.type==='side'?[state.depth*(p.u||1),state.height*(p.v||1)]:p.type==='shelf'?[state.width*(p.u||1),state.depth*(p.v||1)]:[state.width*(p.u||1),state.height*(p.v||1)];for(const v of [i+1,p.type,dims.join(' × '),p.material+' / '+p.color])row.insertCell().textContent=v;}sheet.append(table);if((state.products||[]).length){const heading=document.createElement('h2');heading.textContent='Products and signs';sheet.append(heading);for(const p of state.products){const line=document.createElement('p');line.textContent=`${p.name}: ${p.width} × ${p.height} × ${p.depth} cm; position ${p.x.toFixed(1)}, ${p.z.toFixed(1)} cm; base height ${p.y} cm`;sheet.append(line);}}const notes=document.createElement('p');notes.textContent='Pack matching connectors and verify kit load limits. Numbers identify panels in the views; this is a layout reference, not a certified assembly sequence.';sheet.append(notes);window.print();};
// Direction is drawn only for the active drag, not across the entire scene.
canvas.addEventListener('pointermove',()=>{if(!down?.edge||!down.direction)return;const origin=world(down.edge.mid),vector=new THREE.Vector3();vector[down.direction.axis]=down.direction.sign;const arrow=new THREE.ArrowHelper(vector,origin,Math.min(state.width,state.height,state.depth)*.6,down.erasing?0xcf694f:0xd9992f,3,2);extensionPreview.add(arrow);if(!down.valid&&down.list.length){const reason=down.list.some(p=>p.y<0)?'Below tabletop':down.list.some(p=>Math.abs(p.x)>31||p.y>31||Math.abs(p.z)>31)?'Outside build area':'Overlaps an existing panel';$('#tip').textContent=reason+' · change direction with R or shorten the drag';}if(state.table?.enabled&&down.list.length&&!down.erasing){const t=state.table,inset=Math.max(0,Math.min(20,+$('#tableInset').value||0)),xs=[t.x-t.width/2+inset,t.x+t.width/2-inset],zs=[t.z-t.depth/2+inset,t.z+t.depth/2-inset];for(const [axis,values,unit] of [['x',xs,state.width],['z',zs,state.depth]])for(const value of values){const vertices=down.list.flatMap(CubeModel.vertices),index=axis==='x'?0:2,dist=Math.min(...vertices.map(v=>Math.abs(v[index]*unit-value)));if(dist>3)continue;const a=new THREE.Vector3(axis==='x'?value:xs[0],.2,axis==='z'?value:zs[0]),b=new THREE.Vector3(axis==='x'?value:xs[1],.2,axis==='z'?value:zs[1]);extensionPreview.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:dist<.05?'#58a46e':'#d9992f',depthTest:false})));$('#tip').textContent+=dist<.05?' · aligned to table edge':' · table edge is between panel sizes';}}renderer.render(scene,camera);});
$('#bpKind').onchange=()=>{pendingMesh=null;const kind=$('#bpKind').value;$('#bpName').value=kind==='hook'?'Metal hook':kind==='acrylic'?'Acrylic display stand':'Product';for(const [id,value] of [['bpWidth',kind==='hook'?3:30],['bpHeight',kind==='hook'?4:15],['bpDepth',kind==='hook'?15:24]])$('#'+id).value=value;};AccessoryViews.connect(p=>{pendingMesh=p.mesh;pendingMeshColors=p.meshColors||null;$('#bpName').value=p.name;$('#bpWidth').value=p.width;$('#bpHeight').value=p.height;$('#bpDepth').value=p.depth;saveProduct(true);});
const itemPalette=document.createElement('section');itemPalette.className='itemPalette';itemPalette.innerHTML=`<h2>Stock your booth</h2><div class="itemTabs" role="group" aria-label="Item categories"><button data-item-tab="product" aria-pressed="true">Products</button><button data-item-tab="hook" aria-pressed="false">Hooks</button><button data-item-tab="acrylic" aria-pressed="false">Acrylic</button><button data-item-tab="stand" aria-pressed="false">Custom</button></div><p>Drag a card onto your display. Sizes are editable starting points, in cm.</p><div id="itemCards"></div><button id="editItems">Create / edit an item</button></section>`;productsPanel.before(itemPalette);productsPanel.querySelector('summary').textContent='Item editor & library';productsPanel.open=false;
let paletteTab='product',paletteStamp='',cardDrag=null;
function paletteItems(){const defaults={product:[{name:'Woodland A5 print',art:'forest',width:14.8,height:21,depth:.2},{name:'Night sky A4 print',art:'night',width:21,height:29.7,depth:.2},{name:'Little joys sticker sheet',art:'stickers',width:10,height:15,depth:.2},{name:'Cat charm card',art:'charm',width:5,height:8,depth:.5},{name:'Botanical bookmark',art:'bookmark',width:5,height:15,depth:.1},{name:'Enamel pin set',art:'pins',width:8,height:11,depth:1}],hook:[5,10,15,20].map(depth=>({name:depth+' cm hook',width:3,height:4,depth})),acrylic:[2,3,4,5].map(levels=>({name:levels+'-level stand',width:30,height:levels*5,depth:levels*8,levels})),stand:[]};const list=defaults[paletteTab].map(p=>({...p,kind:paletteTab,image:p.art&&typeof DefaultProductArt!=='undefined'?DefaultProductArt.make(p.art):''})),keyOf=p=>JSON.stringify([p.kind||'product',p.name,p.width,p.height,p.depth,p.kind==='acrylic'?(p.levels||3):null,p.image||'',p.mesh||null,p.meshColors||null]),seen=new Set(list.map(keyOf));for(const p of state.products||[]){if((p.kind||'product')!==paletteTab)continue;const key=keyOf(p);if(!seen.has(key)){seen.add(key);list.push({...p});}}return list;}
function refreshItemPalette(){const stamp=paletteTab+JSON.stringify(state.products||[]);if(stamp===paletteStamp)return;paletteStamp=stamp;const cards=$('#itemCards');cards.replaceChildren();for(const p of paletteItems()){const b=document.createElement('button');b.className='itemCard';b.setAttribute('aria-label','Place '+p.name);const icon=document.createElement('span');icon.className='itemThumb';if(p.image){const img=document.createElement('img');img.src=p.image;img.alt='';img.draggable=false;icon.append(img);}else{icon.innerHTML=p.kind==='hook'?'<svg viewBox="0 0 60 44"><path d="M12 8v24h35l5-7M7 8h10"/></svg>':p.kind==='acrylic'?'<svg viewBox="0 0 60 44"><path d="M5 36h16V26h16V16h17M5 40V36M21 40V26M37 40V16M54 40V16"/></svg>':p.kind==='stand'?'<svg viewBox="0 0 60 44"><path d="M5 38h13V28h13V18h13V8h10M5 38h49V8"/></svg>':'<svg viewBox="0 0 60 44"><rect x="16" y="4" width="28" height="36" rx="2"/><path d="M21 12h18M21 18h18M21 25h12"/></svg>';}
const text=document.createElement('span'),name=document.createElement('b'),size=document.createElement('small');name.textContent=p.name;size.textContent=`${p.width} × ${p.height} × ${p.depth} cm`;text.append(name,size);b.append(icon,text);b.addEventListener('pointerdown',e=>startCard(e,p));b.addEventListener('lostpointercapture',()=>{if(cardDrag?.capture===b)finishCard(true);});b.addEventListener('click',e=>{if(e.detail===0)placeCardAtTable(p);});cards.append(b);}if(!cards.children.length){const note=document.createElement('p');note.textContent='Open the stand editor to design a stand. Transferred stands appear here for reuse.';cards.append(note);}if(paletteTab==='stand'){const b=document.createElement('button');b.textContent='Open display-stand editor';b.onclick=()=>$('#openStandEditor').click();cards.append(b);}}
itemPalette.querySelectorAll('[data-item-tab]').forEach(b=>b.onclick=()=>{paletteTab=b.dataset.itemTab;itemPalette.querySelectorAll('[data-item-tab]').forEach(q=>q.setAttribute('aria-pressed',String(q===b)));refreshItemPalette();});$('#editItems').onclick=()=>{productsPanel.open=!productsPanel.open;if(productsPanel.open)productsPanel.scrollIntoView({block:'nearest',behavior:'smooth'});};
function addPaletteItem(template,position){try{const clean={...template};delete clean.hookId;delete clean.hookOffset;delete clean.trayStandId;delete clean.trayPlane;delete clean.tilt;const p=BoothModel.validateProducts([{...clean,...position,id:crypto.randomUUID(),image:template.image||''}])[0];BoothModel.validateProducts([...(state.products||[]),p]);change(()=>state.products=[...(state.products||[]),p],p.name+' placed.');$('#boothProduct').value=p.id;loadProduct(p);mode='product';document.querySelectorAll('.modes button').forEach(b=>b.classList.toggle('active',b.id==='productMode'));chime(false);}catch(error){$('#status').textContent=error.message;}}
function placeCardAtTable(p){if(p.kind==='hook'){$('#status').textContent='Drag a hook onto a vertical grid panel.';return;}addPaletteItem(p,{x:state.table?.x||0,y:0,z:state.table?.z||0,rotation:0});}
function startCard(e,p){if(e.button!==0||cardDrag)return;e.preventDefault();const object=new THREE.Group();if(p.kind&&p.kind!=='product')AccessoryViews.build(object,p);else{object.add(new THREE.Mesh(new THREE.BoxGeometry(p.width,p.height,p.depth),new THREE.MeshStandardMaterial({color:'#e6c58f',transparent:true,opacity:.8})));if(p.image){const texture=new THREE.TextureLoader().load(p.image,()=>renderer.render(scene,camera));texture.colorSpace=THREE.SRGBColorSpace;const face=new THREE.Mesh(new THREE.PlaneGeometry(p.width,p.height),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false}));face.position.z=p.depth/2+.04;object.add(face);}}object.visible=false;scene.add(object);cardDrag={id:e.pointerId,p,object,target:null,capture:e.currentTarget,x:e.clientX,y:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId);document.body.classList.add('draggingItem');showTrash(true);$('#tip').textContent='Drag onto a panel or tabletop · Esc cancels';}
function moveCard(e){const d=cardDrag;if(!d||d.id!==e.pointerId)return;d.trash=overTrash(e);if(d.trash){d.target=null;d.object.visible=false;$('#tip').textContent='Release to discard this item';renderer.render(scene,camera);return;}d.moved ||= Math.hypot(e.clientX-d.x,e.clientY-d.y)>5;const rect=canvas.getBoundingClientRect();d.target=null;d.object.visible=false;if(e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom){const surface=placementSurface(productPointer(e,d.p,d.lastTarget));
 const allowed=surface&&(d.p.kind==='hook'?surface.object.userData.cell.type!=='shelf':['acrylic','stand'].includes(d.p.kind)?surface.object.userData.cell.type==='shelf':true);const {tier,hook}=accessoryTarget(e,d.p);if(['acrylic','stand'].includes(d.p.kind)&&surface&&surface.object.userData.cell.type!=='shelf'){const floor=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());if(floor)d.target={x:floor.x,y:0,z:floor.z,rotation:0};}if(tier)d.target=tier;else if(hook)d.target=hook;else if(allowed)d.target=AccessoryViews.snap(d.p,surface);else if(!surface&&!state.table?.enabled&&d.p.kind!=='hook'){const point=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());if(point)d.target={x:point.x,y:0,z:point.z,rotation:0};}
 if(d.target?.invalid){$('#tip').textContent=d.target.reason;d.target=null;renderer.render(scene,camera);return;}d.target=BoothModel.snapStand(state,d.p,d.target);if(d.target){d.lastTarget=d.target;d.object.visible=true;d.object.position.set(d.target.x,d.target.y+d.p.height/2,d.target.z);d.object.rotation.order='YXZ';d.object.rotation.set(d.target.tilt||0,d.target.rotation||0,0);$('#tip').textContent=(d.target.hookId?'Release to hang ':'Release to place ')+d.p.name;}else $('#tip').textContent=d.p.kind==='hook'?'Hooks attach to vertical panels': 'Drop onto a suitable panel or tabletop';}renderer.render(scene,camera);}
function finishCard(cancel=false){const d=cardDrag;if(!d)return;cardDrag=null;showTrash(false);if(d.capture.hasPointerCapture(d.id))d.capture.releasePointerCapture(d.id);document.body.classList.remove('draggingItem');scene.remove(d.object);d.object.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});if(!cancel){if(d.trash){$('#status').textContent='Item discarded.';}else if(d.target)addPaletteItem(d.p,d.target);else if(!d.moved)placeCardAtTable(d.p);else $('#status').textContent='Not placed. Drop onto a suitable surface.';}$('#tip').textContent='Drag an item onto a surface · empty space rotates the view';updateCamera();}
window.addEventListener('pointermove',moveCard);window.addEventListener('pointerup',e=>{if(cardDrag?.id===e.pointerId){cardDrag.trash=overTrash(e);finishCard();}});window.addEventListener('pointercancel',()=>finishCard(true));window.addEventListener('blur',()=>finishCard(true));window.addEventListener('keydown',e=>{if(cardDrag&&(e.key==='Escape'||((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'))){e.preventDefault();e.stopImmediatePropagation();finishCard(true);}},true);
syncProducts();refreshItemPalette();
})();
