(function(g){
function validateProducts(raw){if(raw===undefined)return [];if(!Array.isArray(raw)||raw.length>200)throw Error('Maximum 200 products.');if(raw.reduce((sum,p)=>sum+(typeof p?.image==='string'?p.image.length:0),0)>15000000)throw Error('Product artwork exceeds the 15 MB design limit');const ids=new Set();return raw.map(p=>{if(!p||typeof p.id!=='string'||ids.has(p.id))throw Error('Invalid product ID');ids.add(p.id);for(const k of ['width','height','depth'])if(!Number.isFinite(p[k])||p[k]<=0||p[k]>300)throw Error('Invalid product size');for(const k of ['x','y','z'])if(!Number.isFinite(p[k])||Math.abs(p[k])>1500)throw Error('Invalid product position');if(p.image&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.image))throw Error('Invalid product image');if((p.image||'').length>3000000)throw Error('Image too large');if(p.kind&&!['product','hook','acrylic','stand'].includes(p.kind))throw Error('Unknown accessory');if(p.levels!==undefined&&(!Number.isInteger(p.levels)||p.levels<1||p.levels>8))throw Error('Choose 1–8 levels');if(p.rotation!==undefined&&!Number.isFinite(p.rotation))throw Error('Invalid rotation');if(p.mesh&&(!Array.isArray(p.mesh)||p.mesh.length>300000||p.mesh.length%9||!p.mesh.every(v=>Number.isFinite(v)&&Math.abs(v)<1000)))throw Error('Invalid stand mesh');if(p.meshColors&&(!p.mesh||!Array.isArray(p.meshColors)||p.meshColors.length!==p.mesh.length||!p.meshColors.every(v=>Number.isFinite(v)&&v>=0&&v<=1)))throw Error('Invalid stand colours');if(p.hookId!==undefined&&(typeof p.hookId!=='string'||!Number.isFinite(p.hookOffset)))throw Error('Invalid hook attachment');return {...(p.hookId?{hookId:p.hookId,hookOffset:p.hookOffset}:{}),id:p.id,name:String(p.name||'Product').slice(0,80),width:p.width,height:p.height,depth:p.depth,x:p.x,y:p.y,z:p.z,image:p.image||'',...(p.kind?{kind:p.kind}:{}),...(p.levels?{levels:p.levels}:{}),...(p.rotation!==undefined?{rotation:p.rotation}:{}),...(p.mesh?{mesh:p.mesh}: {}),...(p.meshColors?{meshColors:p.meshColors}:{})};});}
function move(panels,keys,delta,copy=false){const chosen=panels.filter(p=>keys.has(CubeModel.panelKey(p))),other=panels.filter(p=>!keys.has(CubeModel.panelKey(p))),moved=chosen.map(p=>({...p,x:+(p.x+delta.x).toFixed(6),y:+(p.y+delta.y).toFixed(6),z:+(p.z+delta.z).toFixed(6)}));if(panels.length+(copy?moved.length:0)>1500)return {error:'Panel limit reached'};if(moved.some(p=>p.y<0||p.y>31||Math.abs(p.x)>31||Math.abs(p.z)>31))return {error:'Outside the build area'};if(moved.some(p=>(copy?panels:other).some(q=>CubeModel.overlaps(p,q))))return {error:'Overlaps an existing panel'};return {panels:[...(copy?panels:other),...moved],moved};}
function snap(state,chosen,delta,inset=0){const t=state.table;if(!t?.enabled||!chosen.length)return {delta,label:''};const points=chosen.flatMap(CubeModel.vertices),out={...delta},labels=[];for(const [axis,k,unit,size,center] of [['x',0,state.width,t.width,t.x],['z',2,state.depth,t.depth,t.z]]){const lo=Math.min(...points.map(v=>v[k]))*unit,hi=Math.max(...points.map(v=>v[k]))*unit,targets=[{v:center-size/2+inset-lo,label:axis==='x'?'Left edge':'Back edge'},{v:center+size/2-inset-hi,label:axis==='x'?'Right edge':'Front edge'}].sort((a,b)=>Math.abs(a.v-delta[axis]*unit)-Math.abs(b.v-delta[axis]*unit));if(Math.abs(targets[0].v-delta[axis]*unit)<=3){out[axis]=targets[0].v/unit;labels.push(targets[0].label);}}return {delta:out,label:labels.join(' + ')};}
function hang(p,hook,offset=0){const rotation=hook.rotation||0;return {x:hook.x+Math.sin(rotation)*offset,y:hook.y-p.height+.5,z:hook.z+Math.cos(rotation)*offset,rotation,hookId:hook.id,hookOffset:offset};}
function moveProduct(products,id,position){const result=products.map(p=>({...p})),item=result.find(p=>p.id===id);Object.assign(item,position);if(!position.hookId){delete item.hookId;delete item.hookOffset;}if(item.kind==='hook')for(const p of result)if(p.hookId===id)Object.assign(p,hang(p,item,p.hookOffset));return result;}
// Resolve both wall axes against the stand footprint, including panel thickness clearance.
function snapStand(state,p,position){
 if(!position||!['acrylic','stand'].includes(p.kind))return position;
 const out={...position},angle=out.rotation||0,c=Math.abs(Math.cos(angle)),s=Math.abs(Math.sin(angle));
 const half={x:(p.width*c+p.depth*s)/2,z:(p.depth*c+p.width*s)/2},gap=.5,range=3;
 const walls=state.panels.filter(q=>q.type!=='shelf').map(q=>{const v=CubeModel.vertices(q).map(a=>[a[0]*state.width,a[1]*state.height,a[2]*state.depth]);return {axis:q.type==='side'?'x':'z',lo:[0,1,2].map(i=>Math.min(...v.map(a=>a[i]))),hi:[0,1,2].map(i=>Math.max(...v.map(a=>a[i])))};});
 for(let pass=0;pass<3;pass++)for(const axis of ['x','z']){
  const i=axis==='x'?0:2,other=axis==='x'?'z':'x',j=axis==='x'?2:0;
  const candidates=walls.filter(w=>w.axis===axis&&out.y+p.height>w.lo[1]&&out.y<w.hi[1]&&out[other]+half[other]>w.lo[j]&&out[other]-half[other]<w.hi[j]).map(w=>{
   const plane=w.lo[i],delta=out[axis]-plane,side=Math.abs(delta)>1e-6?Math.sign(delta):Math.sign((p[axis]??out[axis])-plane)||1;
   return {value:plane+side*(half[axis]+gap),distance:Math.abs(delta)-half[axis]};
  }).filter(w=>w.distance<=range).sort((a,b)=>Math.abs(a.value-out[axis])-Math.abs(b.value-out[axis]));
  if(candidates.length)out[axis]=candidates[0].value;
 }
 return out;
}
function removeProduct(products,id){return products.filter(p=>p.id!==id).map(p=>{if(p.hookId!==id)return p;const out={...p};delete out.hookId;delete out.hookOffset;return out;});}
g.BoothModel={removeProduct,validateProducts,move,snap,hang,moveProduct,snapStand};})(globalThis);
