const {test}=require('node:test'),assert=require('node:assert/strict');require('./model.js');const M=globalThis.CubeModel;const cube=(x=0,y=0,z=0)=>({x,y,z,material:'mesh',color:'#53695e'});const design=(cubes)=>({schema:'cube-studio',version:1,name:'Test',width:35,height:35,depth:35,back:true,cubes});
test('one open cube has five panels and eight connector positions',()=>{const v=M.inventory(design([cube()]));assert.equal(v.panels,5);assert.equal(v.connectors,8);});
test('adjacent cubes share a side and corner connectors',()=>{const v=M.inventory(design([cube(),cube(1)]));assert.equal(v.panels,9);assert.equal(v.connectors,12);});
test('2x2 layout has sixteen panels and eighteen connector positions',()=>{const v=M.inventory(design([cube(),cube(1),cube(0,1),cube(1,1)]));assert.equal(v.panels,16);assert.equal(v.connectors,18);assert.equal(v.unsupported,0);});
test('missing support is reported and open backs remove panels',()=>{const s=design([cube(),cube(1,1)]);assert.equal(M.inventory(s).unsupported,1);s.back=false;assert.equal(M.inventory(s).panels,8);});
test('save/import preserves material and rejects overlaps and invalid dimensions',()=>{const s=design([cube()]);assert.deepEqual(M.validate(JSON.parse(JSON.stringify(s))),s);assert.throws(()=>M.validate({...s,cubes:[cube(),cube()]}),/Duplicate/);assert.throws(()=>M.validate({...s,width:0}),/dimensions/);assert.throws(()=>M.validate({...s,cubes:[cube(0,-1)]}),/position/);});

test('cube migration preserves panels and individual deletion stays deleted',()=>{const s=M.migrate(design([cube(),cube(1)]));assert.equal(s.version,2);assert.equal(s.panels.length,9);s.panels.splice(0,1);const restored=M.migrate(JSON.parse(JSON.stringify(s)));assert.equal(restored.panels.length,8);assert.equal(M.inventory(restored).panels,8);});
test('each attachment adds exactly one unique edge-connected panel',()=>{const s=M.migrate(design([cube()]));for(const type of ['side','back','shelf']){const targets=M.candidates(s,type);assert.ok(targets.length);const next=targets[0];assert.ok(!s.panels.some(p=>M.panelKey(p)===M.panelKey(next)));const before=s.panels.length;s.panels.push({...next,material:'plastic',color:'#112233'});assert.equal(M.validate(s).panels.length,before+1);assert.equal(M.inventory(s).panels,before+1);}});
test('empty panel designs can be saved and restarted in each orientation',()=>{const s=M.migrate(design([cube()]));s.panels=[];assert.equal(M.validate(s).panels.length,0);for(const type of ['side','back','shelf'])assert.deepEqual(M.candidates(s,type),[{type,x:0,y:0,z:0}]);});

test('edge extensions snap to halves and split into full plus half pieces',()=>{const p={type:'back',x:0,y:0,z:0,material:'mesh',color:'#112233'};const half=M.extension(p,'x',1,.45);assert.equal(half.length,1);assert.equal(half[0].u,.5);assert.equal(half[0].x,1);const long=M.extension(p,'x',1,1.5);assert.equal(long.length,2);assert.equal(long[0].u,1);assert.equal(long[1].u,.5);assert.equal(long[1].x,2);assert.equal(M.extension(p,'x',1,-1).length,0);assert.equal(M.extension(p,'y',-1,.5)[0].y,-.5);});
test('half panels round-trip and inventory measures actual sizes',()=>{const s={...M.migrate(design([cube()])),panels:[{type:'back',x:.5,y:0,z:0,u:.5,v:1,material:'mesh',color:'#112233'}]};const restored=M.migrate(JSON.parse(JSON.stringify(s)));assert.equal(restored.panels[0].u,.5);assert.deepEqual(M.inventory(restored).rows[0].dims,[17.5,35]);assert.equal(M.inventory(restored).connectors,4);assert.ok(M.overlaps(s.panels[0],{...s.panels[0],x:0,u:1}));assert.equal(M.overlaps(s.panels[0],{...s.panels[0],x:1}),false);});

test('edge dragging can turn a vertical backdrop into a horizontal shelf',()=>{const p=M.edgeExtension([[0,1,0],[1,1,0]],'z',1,.5)[0];assert.equal(p.type,'shelf');assert.equal(p.y,1);assert.equal(p.u,1);assert.equal(p.v,.5);});
test('half-width edges cannot create quarter panels and Shift creates full panels',()=>{const ends=[[0,0,0],[.5,0,0]];const normal=M.edgeExtension(ends,'y',1,.6);assert.equal(normal[0].u,.5);assert.equal(normal[0].v,1);assert.ok(normal.every(p=>p.u*p.v>=.5));const full=M.edgeExtension(ends,'y',1,1.2,true);assert.ok(full.every(p=>p.u===1&&p.v===1));const old=M.extension({type:'back',x:0,y:0,z:0,u:.5,v:1},'y',1,.6);assert.equal(old[0].v,1);});

test('inward drag retracts contiguous panels after their centres and stops at gaps',()=>{const p={type:'back',x:2,y:0,z:0,u:1,v:1,material:'mesh',color:'#112233'},half={...p,x:1.5,u:.5},far={...p,x:0};assert.equal(M.retraction([p,half,far],p,'x',1,.4).length,0);assert.deepEqual(M.retraction([p,half,far],p,'x',1,.5),[p]);assert.deepEqual(M.retraction([p,half,far],p,'x',1,1.25),[p,half]);assert.deepEqual(M.retraction([p,half,far],p,'x',1,10),[p,half]);});
test('retraction in the other direction preserves neighbouring rows and perpendicular panels',()=>{const p={type:'back',x:0,y:0,z:0},next={...p,x:1},above={...p,y:1},side={...p,type:'side'};assert.deepEqual(M.retraction([p,next,above,side],p,'x',-1,2),[p,next]);});

test('extending halves merges into one full panel in either direction and orientation',()=>{for(const type of ['side','shelf','back'])for(const dim of ['u','v'])for(const sign of [-1,1]){const axes=type==='side'?['z','y']:type==='shelf'?['x','z']:['x','y'],axis=axes[dim==='u'?0:1],p={type,x:1,y:1,z:1,u:1,v:1,material:'mesh',color:'#112233'};p[dim]=.5;const next={...p,[axis]:p[axis]+sign*.5},result=M.addAndMerge([p],[next]);assert.equal(result.panels.length,1);assert.equal(result.panels[0][dim],1);assert.equal(result.panels[0][axis],Math.min(p[axis],next[axis]));assert.equal(result.merged,1);assert.equal(p[dim],.5);}});
test('merge preserves differing finishes and ignores nonadjacent half panels',()=>{const p={type:'back',x:0,y:0,z:0,u:.5,v:1,material:'mesh',color:'#112233'};for(const next of [{...p,x:.5,material:'plastic'},{...p,x:1},{...p,x:.5,y:1}])assert.equal(M.addAndMerge([p],[next]).merged,0);});

test('plastic half-panel extensions retain half dimensions and merge into full plastic panels',()=>{const p={...M.edgeExtension([[0,0,0],[1,0,0]],'y',1,.5)[0],material:'plastic',color:'#112233'};assert.equal(p.u,1);assert.equal(p.v,.5);const next={...p,y:.5},s=M.migrate(design([cube()]));s.panels=[p];assert.deepEqual(M.inventory(s).rows[0].dims,[35,17.5]);const merged=M.addAndMerge([p],[next]);assert.equal(merged.panels.length,1);assert.equal(merged.panels[0].v,1);assert.equal(merged.panels[0].material,'plastic');});

test('inventory counts full and half panels separately across materials and orientations',()=>{const s=M.migrate(design([cube()]));s.panels=[{type:'back',x:0,y:0,z:0,material:'mesh',color:'#112233'},{type:'side',x:1,y:0,z:0,u:.5,v:1,material:'plastic',color:'#112233'},{type:'shelf',x:0,y:1,z:0,u:1,v:.5,material:'mesh',color:'#112233'}];const inv=M.inventory(s);assert.equal(inv.full,1);assert.equal(inv.half,2);assert.equal(inv.panels,3);});
test('Undo restores the layout without changing camera framing',()=>{const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('app.js','utf8');const start=source.indexOf('function history('),end=source.indexOf("$('#undo').onclick",start),ctx=vm.createContext({state:{name:'after'},selected:'panel',render:()=>{},fit:()=>{throw Error('Camera must not reset');},$:()=>({textContent:''})});vm.runInContext(source.slice(start,end),ctx);vm.runInContext(`history(['{"name":"before"}'],[])`,ctx);assert.equal(ctx.state.name,'before');});

test('table saves dimensions and offsets without affecting panel counts',()=>{const s=M.migrate(design([cube()]));s.table={enabled:true,width:180,depth:75,height:74,x:30,z:10};const restored=M.migrate(JSON.parse(JSON.stringify(s)));assert.deepEqual(restored.table,s.table);assert.equal(M.inventory(restored).panels,5);assert.throws(()=>M.validate({...s,table:{...s.table,width:-1}}),/table width/);});

test('table edge alignment is flush, supports corners, and preserves the other axis',()=>{const s=M.migrate(design([cube(-1,0,1),cube(0,0,1)])),t={enabled:true,width:180,depth:75,height:74,x:12,z:8};const left=M.alignTable(s,t,'left');assert.equal(left.x-left.width/2,-35);assert.equal(left.z,8);const right=M.alignTable(s,t,'right');assert.equal(right.x+right.width/2,35);const back=M.alignTable(s,left,'back');assert.equal(back.z-back.depth/2,35);assert.equal(back.x,left.x);const front=M.alignTable(s,t,'front');assert.equal(front.z+front.depth/2,70);assert.equal(t.x,12);assert.equal(s.panels.length,9);});
test('table alignment supports half panels and an empty starter grid',()=>{const s=M.migrate(design([cube()]));s.panels=[{type:'back',x:.5,y:0,z:0,u:.5,v:1,material:'mesh',color:'#112233'}];const t={width:180,depth:75,x:0,z:0};assert.equal(M.alignTable(s,t,'left').x-90,17.5);s.panels=[];assert.equal(M.alignTable(s,t,'right').x+90,35);});

test('a paint stroke applies only to brushed panels in a single edit, or cancels cleanly',()=>{const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('app.js','utf8'),start=source.indexOf('function finishPaint('),end=source.indexOf("canvas.addEventListener('pointerdown'",start);for(const cancel of [false,true]){let edits=0;const panels=[{type:'back',x:0,y:0,z:0,material:'mesh',color:'#112233'},{type:'back',x:1,y:0,z:0,material:'mesh',color:'#112233'}],ctx=vm.createContext({paintStroke:{id:1,keys:new Set([M.panelKey(panels[0])]),style:{material:'plastic',color:'#ffffff'}},canvas:{hasPointerCapture:()=>false},state:{panels},CubeModel:M,change:fn=>{edits++;fn();},render:()=>{}});vm.runInContext(source.slice(start,end),ctx);vm.runInContext(`finishPaint(${cancel})`,ctx);assert.equal(edits,cancel?0:1);assert.equal(panels[0].color,cancel?'#112233':'#ffffff');assert.equal(panels[1].color,'#112233');assert.equal(ctx.paintStroke,null);}});
